production:
  adapter: postgresql
  encoding: utf8
  template: template0
  collate: "it_IT.UTF-8"
  ctype: "it_IT.UTF-8"
  reconnect: false
  database: deploy
  pool: 10
  username: deploy
  host: localhost
